# Seconds Limine waits before booting. Symbiote is meant to come up fast.
timeout: 1

/Symbiote
    protocol: limine
    path: boot():/boot/symbiote
    module_path: boot():/boot/locals.fs
    module_path: boot():/boot/locals.bf
